## 단축키

ESC, a : 현재 셀 바로 위에 새로운 코드 셀 추가

ESC, b : 현재 셀 바로 아래에 새로운 코드 셀 추가

ESC, dd : 현재 셀 삭제

ESC, m : 현재 셀을 Markdown 셀로 변환

ESC, y : 현재 셀을 Code 셀로 변환

ESC, c : 현재 셀 복사

ESC, x : 현재 셀 잘라내기

ESC, v : 복사하거나 잘라낸 셀을 붙여넣기

## _02_Tensors 폴더 모든 예제

### 1. a_tensor_initialization

In [1]:
import torch

# torch.Tensor class
t1  = torch.Tensor([1,2,3], device = 'cpu')
print(t1.dtype)
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print (t1.shape)


torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [2]:
t1_cuda = t1.to(torch.device('cuda'))
t1_cuda = t1.cuda()
t1_cpu = t1.cpu()
print(t1_cuda)
print(t1_cpu)

print("="* 50, 1)

tensor([1., 2., 3.], device='cuda:0')
tensor([1., 2., 3.])
================================================== 1


In [3]:
t2 = torch.tensor([1,2,3], device ='cpu')
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [4]:
t2_cuda = t2.to(torch.device('cuda'))

In [5]:
a1 = torch.tensor(1)
print(a1.shape, a1.ndim)

torch.Size([]) 0


In [6]:
a2 = torch.tensor([1])
print(a2.shape, a2.ndim)

torch.Size([1]) 1


In [7]:
a3 = torch.tensor([1,2,3,4,5])
print(a3.shape, a3.ndim)

torch.Size([5]) 1


In [8]:
a4 = torch.tensor([[1],[2],[3],[4],[5]])
print(a4.shape, a4.ndim)

torch.Size([5, 1]) 2


In [9]:
a111 = a4.clone()
a111 = a111.to(torch.float32)
print(a111.shape)
print(a111)
a112= torch.mean(a111, dim=0)
print(a112)
a113= torch.mean(a111, dim=1)
print(a113)

torch.Size([5, 1])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])
tensor([3.])
tensor([1., 2., 3., 4., 5.])


In [10]:
a5 = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])
print(a5.shape, a5.ndim)

torch.Size([3, 2]) 2


In [11]:
a6 = torch.tensor([           
    [[1],[2]],
    [[3],[4]],
    [[5],[6]]
])
print(a6.shape, a6.ndim)
# 3,2,1

torch.Size([3, 2, 1]) 3


In [12]:
a7 = torch.tensor([                 
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)
# 3,1,2,1

torch.Size([3, 1, 2, 1]) 4


In [13]:
a8 = torch.tensor([
    [[[1,2,3],[2,3,4]]],
    [[[3,1,1],[4,4,5]]],
    [[[5,6,2],[6,3,1]]]
])
print(a8.shape, a8.ndim)
# 3,1,2,3

torch.Size([3, 1, 2, 3]) 4


In [14]:
a9 = torch.tensor([                 
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)
# 3,1,2,3,1

torch.Size([3, 1, 2, 3, 1]) 5


In [15]:
a10 = torch.tensor([                 
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

torch.Size([4, 5]) 2


In [16]:
a10 = torch.tensor([                 
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)
# 4,1,5 

torch.Size([4, 1, 5]) 3


In [17]:
a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1,2,3],[4, 5]]],
    [[[1,2,3],[4, 5]]],
    [[[1,2,3],[4, 5]]],
    [[[1,2,3],[4, 5]]],
])

ValueError: expected sequence of length 3 at dim 3 (got 2)

### b_tensor_initialization_copy

In [18]:
import torch
import numpy as np

l1 = [1,2,3]
t1 = torch.Tensor(l1) # float

l2 = [1,2,3]
t2 = torch.tensor(l2) # int

l3  = [1,2,3]
t3 = torch.as_tensor(l3) # int

l1[0] = 100 
l2[0] = 100
l3[0] = 100

# 위에 작업이 필요한 이유는 :  각각 type이 다른데 값을 int로 넣어주면 어떻게 되는지 파악도 가능하지만, 실제 값이 바뀌는지 파악하기 위함
print(t1)
print(t2)
print(t3)

print("#" * 100)

l4 = np.array([1,2,3])
t4 = torch.Tensor(l4)

l5 = np.array([1,2,3])
t5 = torch.tensor(l5)

l6 = np.array([1,2,3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] =100
l6[0] =100
# 이번에 이 작업이 필요한 이유는 : 타입이 아닌, 실제로 값이 바뀌는지를 파악하기 위함
# 결론 : as_tensor는 원본이 바뀌면 마치 C처럼 연결되어있는 느낌

print(t4)
print(t5)
print(t6)



tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


### c_tensor_initialization_constant_values

In [19]:
import torch

t1 = torch.ones(size=(5,)) # torch.ones(5) 
t1_like = torch.ones_like(input = t1)
print(t1)
print(t1_like)
# tensor([1., 1., 1., 1., 1.])
# tensor([1., 1., 1., 1., 1.])

# 궁금증 : 왜 ones해서 5*5가 아님? 왜 shape = 5,1 ?? -> # 5개의 1로 채워진 1차원 텐서 생성

t2 = torch.zeros(size=(6,))
t2_like = torch.zeros_like(input=t2)
print(t2)
print(t2_like)

# 이거는 위에꺼랑 같은 개념이라 궁금증 해결

t3 = torch.empty(size=(4,))
t3_like = torch.empty_like(input=t3)
print(t3)
print(t3_like)
# tensor([9.4713e-30, 1.4559e-42, 3.0000e+00, 0.0000e+00])
# tensor([9.4714e-30, 1.4559e-42, 3.0000e+00, 0.0000e+00]

# 위에꺼는 왜 저런 값이 나오는지? -> 초기화되지 않은 상태의 메모리를 할당받아서 그렇다. (쓰레기 값)
print(t3.zero_()) # 0으로 초기화해봄. -> 되는지 확인해본건데 되네

t4 = torch.eye(n=3)
print(t4)
# 3*3 단위행렬 생성


tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([7.0065e-45, 0.0000e+00, 3.0000e+00, 0.0000e+00])
tensor([2.3694e-38, 1.4013e-45, 0.0000e+00, 0.0000e+00])
tensor([0., 0., 0., 0.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### d_tensor_initialization_random_values

In [20]:
import torch

t1 = torch.randint(low=10,high=20, size=(1,2))
print(t1)

t2 = torch.rand(size=(1, 3))
print(t2)

t3 = torch.randn(size=(1,3))
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3,2))
print(t4)
# 평균이 10이고, 표준편차가 1인 정규분포에서 값을 뽑아서 3*2 텐서 생성
# 저렇다면 저거들 다 더하고 나누면 평균 10이 되나? -> 이론적으로는 맞지만, 실제로는 다를 수 있음
print(torch.mean(t4)) # tensor(9.9343)이 나오네

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)
# 0부터 시작해서 5까지 3등분 혹은 3 걸음

t6 = torch.arange(5)
print(t6)
# 0부터 4까지 그래서 5개의 숫자가 생성

print("#" * 30)

torch.manual_seed(1729)
random1 = torch.rand(2,3)
print(random1)
# seed 를 고정시켜서 random 값이 항상 동일함

random4 = torch.rand(2,3)
print(random4)
# 위에서 이미 고정해서 똑같은 값이 나오는 것.


tensor([[13, 10]])
tensor([[0.9918, 0.1667, 0.2059]])
tensor([[ 1.9037, -0.6024,  0.7043]])
tensor([[ 8.0602,  8.0026],
        [10.8716, 10.1955],
        [ 9.2158,  8.3684]])
tensor(9.1190)
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


### e_tensor_type_conversion

In [21]:
import torch
a = torch.ones((2,3)) # torch.ones(2,3)와 동일한것으로 파악함 이유는? ->
print(a.dtype)

b = torch.ones((2,3), dtype = torch.int16)
print(b.dtype)

c = torch.rand((2,3), dtype = torch.float64) * 20.
print(c.dtype)

d = b.to(torch.int32)
print(d)

double_d = torch.ones(10, 20, dtype= torch.double)
short_e = torch.tensor([1,2], dtype=torch.short)

double_d = torch.zeros(10,2).double() # float64 로 받기
short_e = torch.ones(10, 2 ).short() # int16 으로 받기

double_d = torch.zeros(10, 2).to(torch.double) # float64 로 받기
short_e = torch.ones(10, 2).to(dtype=torch.short) # int16 으로 받기

double_d = torch.zeros(10, 2).type(torch.double) # float64 로 받기
short_e = torch.ones(10,2).type(dtype =torch.short) # int16 으로 받기

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float32
torch.int16
torch.float64
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


### f_tensor_operations

In [22]:
import torch
t1 = torch.ones(size =(2,3))
t2 = torch.ones(size=(2,3))
t3 =torch.add(t1,t2)
t4 = t1 +t2
print(t3)
print(t4)

print("#" * 30)

t5 = torch.sub(t1, t2)
t6 = t1 -t2
print(t5)
print(t6)
# 예상으론 2,3 으로 둘다 0으로 채워짐
print("#" * 30)

t7 = torch.mul(t1,t2)
t8 = t1 * t2
print(t7)
print(t8)
# 예상으론 2,3 으로 둘 다 1로 채워짐 
print("#" * 30)

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)
# 예상으론 2,3 으로 둘 다 1로 채워짐

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


### g_tensor_operations_mm Re

In [23]:
import torch
t1 = torch.dot(
    torch.tensor([2,3]), torch.tensor([2,1])
)
print(t1, t1.size())

t2 = torch.randn(2,3)
t3 = torch.randn(3,2)
t4 = torch.mm(t2,t3) # matrix multiplication라고 한국말론 행렬곱이라고 한다. 계산법은 ? -> 2*3 , 3*2 -> 2*2
print(t4,t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6) # batch matrix multiplication라고 한국말론 배치 행렬곱? 이라고 한다. 계산법은 ? -> 10개의 3*4 , 10개의 4*5 -> 10개의 3*5
print(t7.size())


tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


dot

mm

bmm


### h_tensor_operations_matmul Re

In [24]:
import torch
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1,t2).size())
# 근데 이부분에는 왜 size가 안나오지? -> 스칼라 값이기 때문에 그런듯
# 암묵적으로 2차원으로 되어야 뭔가 더 해주거나 하는듯
t3 = torch.randn(3,4)
t4 = torch.randn(4)
print(torch.matmul(t3,t4).size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5,t6).size())
# 이 경우에는 
# t6을  (10), 4, (1) 이렇게 보는건가 싶음

t7 = torch.randn(10,3,4)
t8 = torch.randn(10, 4,5)
print(torch.matmul(t7, t8).size())

t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4,5)
print(torch.matmul(t9,t10).size())
# 이 부분 조금 이해 안감 배치 사이즈는 그냥 맞춰준다는거야?
# 근데 생각해보니 대량의 데이터의 배치라고 지금 생각해서 그렇지, 컴퓨터가 보기엔 그냥 하나의 차원일 뿐 아닌가? 싶음. 그래서 문제가 없겠다는 생각이 드네.
# 그래서 ndim의 개수가 안맞는데 matmul을 하는 경우에는 앞자리를 맞춰주겠구나 싶고, 

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


matmul

### i_tensor_broadcasting Re

In [25]:
import torch
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1*t2)

print("#" * 50, 1)

t3 = torch.tensor([[0, 1 ], [2,4], [10, 10]])
t4 = torch.tensor([4,5])
print(t3-t4)

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.],[3.,4.]])
print(t5 + 2.0)
print(t5 * 2.0)
print(t5 / 2.0)
print(t5 - 2.0)

print("#" * 50, 3)

def normalize(x):
    return x /255

t6 =torch.randn(3,28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

t7 = torch.tensor([[1,2],[0,3]])
t8 = torch.tensor([[3,1]])
t9 = torch.tensor([[5],[2]])
t10 = torch.tensor([7])
print(t7 + t8) # 2,2 + 1,2 -> 2,2
print(t7 + t9) 
print(t8 + t9)
print(t7 + t10)

print("#" * 50 ,5)

t11 = torch.ones(4,3,2)
t12 = t11 * torch.rand(3,2)
print(t12.shape)

t13 = torch.ones(4,3,2)
t14 = t13 * torch.rand(3,1)
print(t14.shape)

t15 = torch.ones(4,3,2)
t16 = t15 * torch.rand(1,2)
print(t16.shape)

t17 = torch.ones(5,3,4,1)
t18 = torch.rand(3,1,1)
print((t17 + t18).size())

print("#" * 50 ,6)

t19 = torch.empty(5,1,4,1)
t20 = torch.empty(3,1,1)
print((t19 + t20).size())

t21 = torch.empty(1)
t22 = torch.empty(3,1,7)
print((t21 + t22).size())

t23 = torch.ones(3,3,3)
t24 = torch.ones(3,1,3)
print((t23 + t24).size())

print("#" * 50 ,7)

t27 = torch.ones(4) * 5
print(t27)

t28 = torch.pow(t27, 2)
print(t28)

exp = torch.arange(1., 5.)
a = torch.arange(1.,5.)
t29 = torch.pow(a, exp)
print(t29)


tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

pow

### j_linear_regression_dataset_dataloader Re

In [26]:
import torch
from torch.utils.data import Dataset, DataLoader, random_split


class LinearRegressionDataset(Dataset):
  def __init__(self, N=50, m=-3, b=2, *args, **kwargs):
    # N: number of samples, e.g. 50
    # m: slope
    # b: offset
    super().__init__(*args, **kwargs)

    self.x = torch.rand(N, 2)
    self.noise = torch.rand(N) * 0.2
    self.m = m
    self.b = b
    self.y = (torch.sum(self.x * self.m) + self.b + self.noise).unsqueeze(-1)

  def __len__(self):
    return len(self.x)

  def __getitem__(self, idx):
    return self.x[idx], self.y[idx]

  def __str__(self):
    str = "Data Size: {0}, Input Shape: {1}, Target Shape: {2}".format(
      len(self.x), self.x.shape, self.y.shape
    )
    return str


if __name__ == "__main__":
  linear_regression_dataset = LinearRegressionDataset()

  print(linear_regression_dataset)

  print("#" * 50, 1)

  for idx, sample in enumerate(linear_regression_dataset):
    input, target = sample
    print("{0} - {1}: {2}".format(idx, input, target))

  train_dataset, validation_dataset, test_dataset = random_split(linear_regression_dataset, [0.7, 0.2, 0.1])

  print("#" * 50, 2)

  print(len(train_dataset), len(validation_dataset), len(test_dataset))

  print("#" * 50, 3)

  train_data_loader = DataLoader(
    dataset=train_dataset,
    batch_size=4,
    shuffle=True
  )

  for idx, batch in enumerate(train_data_loader):
    input, target = batch
    print("{0} - {1}: {2}".format(idx, input, target))


Data Size: 50, Input Shape: torch.Size([50, 2]), Target Shape: torch.Size([50, 1])
################################################## 1
0 - tensor([0.2638, 0.0148]): tensor([-145.3462])
1 - tensor([0.3347, 0.0177]): tensor([-145.3580])
2 - tensor([0.5295, 0.3932]): tensor([-145.4544])
3 - tensor([0.0152, 0.2740]): tensor([-145.3279])
4 - tensor([0.2562, 0.1772]): tensor([-145.3158])
5 - tensor([0.7240, 0.2712]): tensor([-145.3107])
6 - tensor([0.5282, 0.1365]): tensor([-145.3034])
7 - tensor([0.5036, 0.5921]): tensor([-145.4119])
8 - tensor([0.8255, 0.5440]): tensor([-145.3471])
9 - tensor([0.6687, 0.6091]): tensor([-145.4089])
10 - tensor([0.6253, 0.9405]): tensor([-145.3800])
11 - tensor([0.6994, 0.4283]): tensor([-145.4230])
12 - tensor([0.3099, 0.3567]): tensor([-145.4594])
13 - tensor([0.6212, 0.9794]): tensor([-145.3226])
14 - tensor([0.0826, 0.7808]): tensor([-145.2762])
15 - tensor([0.5381, 0.1021]): tensor([-145.4636])
16 - tensor([0.2985, 0.2210]): tensor([-145.3118])
17 - te

### k Re

In [27]:
import os

import torch
from PIL import Image
from torch.utils.data import Dataset, DataLoader, random_split
from torchvision import transforms

class DogCat2DImageDataset(Dataset):
    def __init__(self):
        self.image_transforms = transforms.Compose([
            transforms.Resize(size=(256, 256)),
            transforms.ToTensor()
        ])
        
        
        dogs_dir = os.path.join(os.path.pardir, "_00_data", "a_image-dog") 
        cats_dir = os.path.join(os.path.pardir, "_00_data", "b_image-cats")  

        image_lst = [
            Image.open(os.path.join(dogs_dir, "bobby.jpg")),
            Image.open(os.path.join(cats_dir, "cat1.png")),
            Image.open(os.path.join(cats_dir, "cat2.png")),
            Image.open(os.path.join(cats_dir, "cat3.png"))
        ]
        print("초기 image_lst :", len(image_lst)) # 초기 image_lst : 4
        image_lst = [self.image_transforms(img) for img in image_lst]
        print("resize된 image_lst :", len(image_lst)) # resize된 image_lst : 4
        self.images = torch.stack(image_lst, dim=0)
        print("stack된 self.images :", self.images.shape) #  torch.Size([4, 3, 256, 256])
        self.image_labels = torch.tensor([[0], [1], [1], [1]])
        print("self.image_labels :", self.image_labels.shape) # torch.Size([4, 1])
        assert len(self.images) == len(self.image_labels) # 에러 안나는것을 보니 동일한가봄

    def __len__(self):
        return len(self.images)
    
    def __getitem__(self, idx):
        return self.images[idx], self.image_labels[idx]
    
    def __str__(self):
        str = "Data Size: {0}, input Shape: {1}, Target Shape: {2}".format(
            len(self.images), self.images.shape, self.image_labels.shape
        )
        return str
if __name__ == "__main__":
    dog_cat_2d_image_dataset = DogCat2DImageDataset()
    print(dog_cat_2d_image_dataset)
    print("dog_cat_2d_image_dataset.images.shape : ",dog_cat_2d_image_dataset.images.shape)
    print("#" * 50, 1)

    for idx, sample in enumerate(dog_cat_2d_image_dataset):
        # enmuerate : 인덱스와 함께 값을 반환
        input, target = sample
        print("{0} - {1}: {2}".format(idx, input.shape, target))

    '''
    0 - torch.Size([3, 256, 256]): tensor([0])
    1 - torch.Size([3, 256, 256]): tensor([1])
    2 - torch.Size([3, 256, 256]): tensor([1])
    3 - torch.Size([3, 256, 256]): tensor([1])
    '''
    train_dataset, test_dataset = random_split(dog_cat_2d_image_dataset, [0.7, 0.3])
    print("train_dataset 길이 : ", len(train_dataset))  # .size()를 len()으로 수정
    print("test_dataset 길이 : ", len(test_dataset))  # .size()를 len()으로 수정
    '''train_dataset 길이 :  3
    test_dataset 길이 :  1'''
    print("#" * 50, 2)

    print(len(train_dataset), len(test_dataset))

    print("#" * 50, 3)

    train_data_loader = DataLoader(
        dataset=train_dataset,
        batch_size = 2,
        shuffle =True
    )
    print("train_data_loader 길이 : ", len(train_data_loader))  # .size를 len()으로 수정
    '''
    train_data_loader 길이 :  2
    0 - torch.Size([2, 3, 256, 256]): tensor([[0],
            [1]])
    1 - torch.Size([1, 3, 256, 256]): tensor([[1]])
    '''
    for idx, batch in enumerate(train_data_loader):
        input, target = batch
        print("{0} - {1}: {2}".format(idx, input.shape, target))




초기 image_lst : 4
resize된 image_lst : 4
stack된 self.images : torch.Size([4, 3, 256, 256])
self.image_labels : torch.Size([4, 1])
Data Size: 4, input Shape: torch.Size([4, 3, 256, 256]), Target Shape: torch.Size([4, 1])
dog_cat_2d_image_dataset.images.shape :  torch.Size([4, 3, 256, 256])
################################################## 1
0 - torch.Size([3, 256, 256]): tensor([0])
1 - torch.Size([3, 256, 256]): tensor([1])
2 - torch.Size([3, 256, 256]): tensor([1])
3 - torch.Size([3, 256, 256]): tensor([1])
train_dataset 길이 :  3
test_dataset 길이 :  1
################################################## 2
3 1
################################################## 3
train_data_loader 길이 :  2
0 - torch.Size([2, 3, 256, 256]): tensor([[1],
        [1]])
1 - torch.Size([1, 3, 256, 256]): tensor([[0]])


### L - Re

In [28]:
import torch

t1 = torch.zeros([2,1,3])
t2 = torch.zeros([2,3,3])
t3 = torch.zeros([2,2,3])

t4 = torch.cat([t1, t2,t3], dim=1)
print(t4.shape) 
# 예상 : 3, 2, 3, 3
# 결과 : torch.Size([2, 6, 3])
print("#" * 50, 1)

t5 =torch.arange(0,3) # 값 : 
t6 = torch.arange(3,8) # 값 :  
# tensor([0, 1, 2]) tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)
print(t7)
# 예상 : 3, 3
# 결과 : 8
# tensor([0, 1, 2, 3, 4, 5, 6, 7])
print("#" * 50, 2)

t8 = torch.arange(0,6).reshape(2,3)
t9 = torch.arange(6,12).reshape(2,3)

t10 = torch.cat((t8, t9), dim=0)
print(t10.size()) 
print(t10)
# 예상 : 2,3
# 결과 : torch.Size([4, 3])
# tensor([[ 0,  1,  2],
#         [ 3,  4,  5],
#         [ 6,  7,  8],
#         [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim= 1)
print(t11.size())
print(t11)
# 예상 : 3, 2
# 결과 : torch.Size([2, 6])
# tensor([[ 0,  1,  2,  6,  7,  8],
        # [ 3,  4,  5,  9, 10, 11]])
print("#" * 50, 3)

t12 = torch.arange(0,6).reshape(2,3)
t13 = torch.arange(6, 12).reshape(2,3)
t14 = torch.arange(12,18).reshape(2,3)

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())
print(t15)
# 예상 : 3, 2, 3
# 결과 : 
'''torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])'''
t16 = torch.cat((t12, t13, t14), dim=1)
print(t15.size())
print(t15)
# 예상 : 3, 3, 2
# 결과 : 
'''
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])'''
print("#" *50, 4)

t17 = torch.arange(0, 6).reshape(1,2,3)
t18 = torch.arange(6, 12).reshape(1,2,3)

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())
print(t19)
# 예상 : 2, 1, 2, 3
# 결과 : 
'''torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])'''
t20 = torch.cat((t17,t18), dim=1)
print(t20.size())
print(t20)
# 예상 : 
# 결과 : 
'''
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])'''
t21 = torch.cat((t17, t18), dim= 2)
print(t21.size())
print(t21)
# 예상 : 
# 결과 : 
'''
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])'''

torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
        

'\ntorch.Size([1, 2, 6])\ntensor([[[ 0,  1,  2,  6,  7,  8],\n         [ 3,  4,  5,  9, 10, 11]]])'

arange -> reshape

cat + dim 0, 1

### m Re

In [29]:
import torch

t1 = torch.tensor([[1,2,3], [4,5,6]]) # 2 3
t2 = torch.tensor([[7,8,9], [10,11,12]]) # 2 3

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim= 1)
t6 = torch.cat([t1.unsqueeze(dim =1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1,t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)],dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0,3)
t10 = torch.arange(3,6)

print( t9.size(), t10.size())

t11 = torch.stack((t9, t10), dim= 0)
print(t11.size())
print(t11)

t12 = torch.cat ((t9.unsqueeze(0), t10.unsqueeze(0)),dim =0)
print(t11.equal(t12))

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())
print(t13)

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


Stack

cat

unsqueeze

dim =0

dim = 1

### n Re

In [30]:
import torch
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
t3 = torch.vstack((t1, t2))
print(t3)

t4 = torch.tensor([[1],[2],[3]])
t5 = torch.tensor([[4],[5],[6]])
t6 = torch.vstack((t4, t5))

t7 = torch.tensor([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(t7.shape)

t8 = torch.tensor([
    [[13,14,15], [16,17,18]],
    [[19,20,21],[22,23,24]]
])
print(t8.shape)

t9 = torch.vstack([t7,t8])
print(t9.shape)
print(t9)

print("#" * 50, 1)

t10 = torch.tensor([1,2,3])
t11 = torch.tensor([4,5,6])
t12 = torch.hstack((t10, t11))
print(t12)

t13 = torch.tensor([[1],[2],[3]])
t14 = torch.tensor([[4],[5],[6]])
t15 = torch.hstack((t13, t14))
print(t15)

t16 = torch.tensor([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(t16.shape)

t17 = torch.tensor([
    [[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24]]
])
print(t17.shape)

t18 = torch.hstack([t16,t17])
print(t18.shape)

print(t18)


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


vstack

hstack